import './styles/test.scss'
import './components/vmd-app.component'
import './components/vmd-tranche-age-selector.component'
import './components/vmd-departement-selector.component'
import './views/vmd-home.view'
import './views/vmd-rdv.view'
