import './styles/global.scss'
import './vmd-app.component'
import './components/vmd-tranche-age-selector.component'
import './components/vmd-departement-selector.component'
import './views/vmd-home.view'
import './views/vmd-rdv.view'
import './views/vmd-centres.view'
import './components/vmd-appointment-card.component'
