import './vmd-app.component'
import './components/vmd-search.component'
import './components/vmd-appointment-card.component'
import './components/vmd-appointment-metadata.component'
import './components/vmd-commune-or-departement-selector.component'
import './components/vmd-button-switch.component'
