name: Déploiement Vite ma dose

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14.12"
      - run: npm ci
      - run: npm run build
        env:
          BASE_URL:  "/"
      - name: rsync deployments
        uses: burnett01/rsync-deployments@4.1
        with:
          switches: -avz --delete --exclude ".git*"
          path: ./dist/
          remote_path: ${{ secrets.DEPLOY_PATH }}
          remote_host: ${{ secrets.DEPLOY_IP }}
          remote_user: ubuntu
          remote_key: ${{ secrets.DEPLOY_KEY }}
